fragment AllProjectFields on Project {
  _id
  name
  summary
  color
  mainImage {
    asset {
      url
    }
  }
  slug {
    current
  }
  category {
    name
  }
  companyLogo {
    asset {
      url
    }
  }
  companyUrl
  deliverables
}
