fragment ProjectFields on Project {
  name
  summary
  color
  mainImage {
    asset {
      url
    }
  }
  projectImages {
    image {
      asset {
        url
      }
    }
    caption
  }
  overviewRaw
  problemRaw
  solutionRaw
  companyLogo {
    asset {
      url
    }
  }
  companyUrl
  jobTitle
  technologies {
    _id
    name
  }
  deliverables
  locations
  category {
    name
  }
}
