import type { AppProps } from "next/app";
import Head from "next/head";
import { ReactNode } from "react";
import { Provider } from "urql";
import { client } from "../client";
import "../styles/globals.css";
import { Page } from "../types/app";

type Props = AppProps & {
  Component: Page;
};

export default function App({ Component, pageProps }: Props) {
  const getLayout = Component.getLayout ?? ((page: ReactNode) => page);

  return (
    <div className="flex flex-col bg-gradient-to-t from-dark-gray to-gray-800 text-white  text-xs overflow-x-hidden">
      <Head>
        <title>Rowland Williams</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider value={client}>
        {getLayout(<Component {...pageProps} />)}
      </Provider>
    </div>
  );
}
