import Head from "next/head";
import { Projects } from "../components/Projects/Projects";
import styles from "../styles/Home.module.css";
import { Project } from "../types/projects";
import { querySanityCms } from "../utils/querySanityCms";

interface Props {
  projects: Project[];
}

export default function Home({ projects }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rowland Williams</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="font-medium py-4 text-base">Rowland Williams</nav>
      <Projects projects={projects} />
    </div>
  );
}

const query = `
		query {
			allProject {
				name,
				technologies,
				startDate,
				endDate, 
				logo {
					asset {
						url
					}
				}
			}
		}
	`;

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const projects = await querySanityCms(query);

  // Pass data to the page via props
  return { props: { projects } };
}
